#!/bin/sh
# ─────────────────────────────────────────────────────────────────────────
# ci_post_clone.sh — runs after Xcode Cloud clones the repo
#
# Generates Apple/lumen/Config/Secrets.xcconfig from Xcode Cloud
# Environment Variables (set in App Store Connect → Xcode Cloud → Workflow).
#
# Required env vars (must be marked "Secret" in Xcode Cloud):
#   - OPENAI_API_KEY
#   - ANTHROPIC_API_KEY
# ─────────────────────────────────────────────────────────────────────────

echo "ci_post_clone.sh: generating Secrets.xcconfig from environment variables"

CONFIG_DIR="$CI_PRIMARY_REPOSITORY_PATH/Apple/lumen/Config"
SECRETS_FILE="$CONFIG_DIR/Secrets.xcconfig"

mkdir -p "$CONFIG_DIR"

if [ -z "$OPENAI_API_KEY" ]; then
  echo "⚠️  OPENAI_API_KEY not set — using placeholder"
  OPENAI_API_KEY="MISSING_IN_CI"
fi

if [ -z "$ANTHROPIC_API_KEY" ]; then
  echo "⚠️  ANTHROPIC_API_KEY not set — using placeholder"
  ANTHROPIC_API_KEY="MISSING_IN_CI"
fi

cat > "$SECRETS_FILE" <<XCC
// Generated by ci_post_clone.sh — do not commit
OPENAI_API_KEY = $OPENAI_API_KEY
ANTHROPIC_API_KEY = $ANTHROPIC_API_KEY
XCC

echo "✓ Secrets.xcconfig generated at $SECRETS_FILE"
