import Foundation

enum AIProvider: String, Sendable, Codable, Hashable {
    case openai
    case anthropic
    case apple
    case supportTemplate
    case queued
}

enum AIResponseMode: String, Sendable, Codable, Hashable {
    case auto
    case manualRegenerate
    case fallbackOnDevice
    case fallbackQueued
    case fallbackTemplate
    case askLumen
}

nonisolated struct AIResponse: Identifiable, Sendable, Codable, Hashable {
    let id: UUID
    let ritualId: UUID
    /// Short concrete title returned by the literary synthesis prompt. Optional
    /// so legacy provider responses and support templates keep decoding.
    let imageKey: String?
    /// The single calm phrase the V11 synthesis screen renders as a 48pt
    /// serif hero. Persistently stored as `intention` for backwards-compat
    /// with the V10 prompt JSON shape (the prompt now asks the model to
    /// keep this to ≤14 words and treat it as a standalone quote).
    let intention: String
    /// Supplementary lines from the V10 shape — preserved on disk for any
    /// downstream consumer (TTS narration, future "expand" affordance) but
    /// no longer rendered as separate blocks on the synthesis screen.
    let focus: [String]
    let reminder: String
    /// Per-dashboard-card mirror lines generated by the prompt. Unknown
    /// categories are ignored during generated-output decoding.
    let categoryInsights: [DashboardCategory: String]?
    let provider: AIProvider
    let mode: AIResponseMode
    let generatedAt: Date

    /// V11 facade: the synthesis screen renders this single line as the
    /// hero quote. Mapping is intentionally trivial — the prompt change
    /// (in PromptBuilder.systemPrompt) is what shortens the underlying
    /// `intention` to a one-sentence quote.
    var heroQuote: String { intention }

    init(
        id: UUID = UUID(),
        ritualId: UUID,
        imageKey: String? = nil,
        intention: String,
        focus: [String],
        reminder: String,
        categoryInsights: [DashboardCategory: String]? = nil,
        provider: AIProvider,
        mode: AIResponseMode,
        generatedAt: Date = Date()
    ) {
        self.id = id
        self.ritualId = ritualId
        self.imageKey = imageKey
        self.intention = intention
        self.focus = focus
        self.reminder = reminder
        self.categoryInsights = categoryInsights?.isEmpty == true ? nil : categoryInsights
        self.provider = provider
        self.mode = mode
        self.generatedAt = generatedAt
    }

    static func decodeGeneratedJSON(
        _ data: Data,
        ritualId: UUID,
        provider: AIProvider,
        mode: AIResponseMode,
        generatedAt: Date = Date()
    ) throws -> AIResponse {
        let output = try JSONDecoder().decode(GeneratedOutput.self, from: data)
        return AIResponse(
            ritualId: ritualId,
            imageKey: output.imageKey,
            intention: output.intention,
            focus: output.focus,
            reminder: output.reminder,
            categoryInsights: output.categoryInsights,
            provider: provider,
            mode: mode,
            generatedAt: generatedAt
        )
    }
}

private struct GeneratedOutput: Decodable {
    let imageKey: String?
    let intention: String
    let focus: [String]
    let reminder: String
    let categoryInsights: [DashboardCategory: String]?

    private enum CodingKeys: String, CodingKey {
        case imageKey
        case intention
        case focus
        case reminder
        case categoryInsights
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        imageKey = Self.trimmedOptional(try container.decodeIfPresent(String.self, forKey: .imageKey))
        intention = try container.decode(String.self, forKey: .intention)
        focus = try container.decode([String].self, forKey: .focus)
        reminder = try container.decode(String.self, forKey: .reminder)

        let rawInsights = try container.decodeIfPresent([String: String].self, forKey: .categoryInsights) ?? [:]
        var parsed: [DashboardCategory: String] = [:]
        for (key, value) in rawInsights {
            guard let category = DashboardCategory(rawValue: key),
                  let trimmed = Self.trimmedOptional(value) else {
                continue
            }
            parsed[category] = trimmed
        }
        categoryInsights = parsed.isEmpty ? nil : parsed
    }

    private static func trimmedOptional(_ value: String?) -> String? {
        guard let trimmed = value?.trimmingCharacters(in: .whitespacesAndNewlines),
              !trimmed.isEmpty else {
            return nil
        }
        return trimmed
    }
}
